### ISSUE TITLE
Filter_labels_tst.txt file not found

### ISSUE THREAD

**Issue by hdm30** [Extreme-classification/siamesexml#3]
Hello, 

I tried the model for custom dataset but i had the following issue:
OSError: /XX/XX/filter_labels_test.txt not found.
My question is how should i proceed to prepare filter_labels_test.txt, i can't find any explanation in the github repo.

Many thanks in advance.

**Comment by kunaldahiya** [comment]
Hi,

If your dataset doesn't need to filter - please create an empty file with the correct name. 

In general, the filter file is used so that the model is neither rewarded nor penalized for making "trivial" predictions. Please refer to "Reciprocal-pair Removal" and "Reciprocal-pair Removal" on [The Extreme Classification Repository](http://manikvarma.org/downloads/XC/XMLRepository.html) for more details.
